### ISSUE TITLE
centre label ?

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-metric-hierarchy#1]
At the moment on the main page of the repository the example says:
`Example wmo_wis2_gc_messagesreceived{center=deu}`

Two points:
- should we use centre-id (as we have in the MQTT topic hierarchy) for the label
- should we use the same value for the centre-id (as we have in the MQTT topic hierarchy)

So the example would read:

`Example wmo_wis2_gc_messagesreceived{centre-id=globalcachedwd}`

globalcachedwd being a tentative name for the time being...

**Comment by antje-s** [comment]
+1 for using the same values for the "centre-id" in topic hierarchy and metrics

**Comment by golfvert** [comment]
Shall we also include the 3-letter country name in front of the centre-id?
So with the same example above:

`wmo_wis2_gc_messagesreceived{centre-id=deu_globalcachedwd}`

The centre-id might not be globally unique (especially for wis2 Nodes. It could mess up the metrics without the country...

**Comment by kaiwirt** [comment]
I would suggest to have both. centre-id being the same as the one in the topics. And country being the 3-letter country code. 

In case of data that could then become centre-id: The center that is reporting and country: The 3-letter code of the country from which the data (observations etc. ) are.

**Comment by golfvert** [comment]
Alternative... Two labels.

`wmo_wis2_gc_messagesreceived{country=deu, centre-id=globalcachedwd}`

So, in the name of the metric we have either gc gb, gdc, wis2node,... and in the labels country and centre-id.

**Comment by antje-s** [comment]
Proposal sounds good for Global Services, how to handle not unique centre-ids for nodes? Should we require that no duplication is allowed in the center-id list? then the problem would be solved...

**Comment by golfvert** [comment]
That is the other option... centre-id might be globally unique.

**Comment by kaiwirt** [comment]
I would not like to have centre-id and country code in the metric name. That is the model case for labels. 

As for centre-id i would use the same names as in the topic. So no globalcachedwd but dwd-offenbach

**Comment by kaiwirt** [comment]
The centre-id discussion is here https://github.com/wmo-im/wis2-topic-hierarchy/issues/5

**Comment by golfvert** [comment]
So, for the time being let's aim at having the centre-id globally unique.
Reusing the same example and based on Kai's comment that would give:

`wmo_wis2_gc_messagesreceived{centre-id=dwd-offenbach}`
`wmo_wis2_gb_activenodes{centre-id=meteo-france-toulouse}`

**Comment by antje-s** [comment]
We should include for the metric 
wmo_wis2_gc_messagesreceived
the additional label "country" as source/originator information as proposed from you, e.g.
wmo_wis2_gc_messagesreceived{country=deu, centre-id=dwd-offenbach}

This would then allow a direct comparison between different GCs per country (same country-label value, different centre-id)

**Comment by kaiwirt** [comment]
Just discovered, that centre-id is an invalid label name. How about centre_id

**Comment by kaiwirt** [comment]
We need to specify the meaning of centre_id and country in the metrics.

Currently my point of view was to have centre_id and country being the centre that provides the metric. So in our case dwd-offenbach and deu.

However how to we express the number of messages received from Sweden in Offenbach?
- centre_id SMHI, country = SWE, Label Name for the reporting centre?
- Is this a use case for the monitoring or do we only want to expose the total number of messages? In that case centre_id would always be dwd-offenbach for us

So Option 1:
centre_id: Name of the centre for which the metric applies (not the one reporting the metric)
country: Name of the country for which the metric applies (not the one reporting the metric)
reporting: Name of the centre reporting the metric
Example: centre_id: ESWI, country: swe, reporting dwd-offenbach

Option 2:
centre_id: Name of the centre providing the metric
country: Name of the country for centre_id
Example: centre_id dwd-offenbach, country: deu (for all metrics provided by dwd-offenbach)

**Comment by golfvert** [comment]
I'd go for option 1. We also have to remember that in prometheus we have endpoints. So, a Global Monitoring center fetching metrics from endpoints DWD GC or France GB or... will know where the metric is coming from. An extra label called job will be created by Prometheus.
I think we do not require the "reporting" label.

**Comment by golfvert** [comment]
Here are the metrics (tentatively) implemented on Météo-France Global Broker since April 9th :
- wmo_wis2_gb_messages_received = number of messages received by the anti-loop companion
- wmo_wis2_gb_messages_invalid = number of invalid messages received 
- wmo_wis2_gb_messages_published = number of messages published after anti-loop detection
The following labels have been defined:
- country
- centre_id 
for the country and centre_id corresponding to the WIS2 Node (See option 1 above)

- report_by = the name of the centre (typically Météo-France Global Broker so meteofrance) reporting the metrics

- job is automatically added by prometheus. It represents the "source" of the metric. 

For filtering purposes, metric names and the labels (country, centre_id, report_by) should be sufficient.
