### ISSUE TITLE
define alert rule for missing GDC metadata archive

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-metric-hierarchy#13]
In cases where a GDC does not produce a metadata archive zipfile on a daily basis (noting the 24 hour retention time for GC), there exists a risk / gap in not being able to cold start a GDC from a known archive.  Consider raising an alert in this case.

**Comment by kaiwirt** [comment]
What are suitable solutions for this?

GC providing a metric with the time stamp of the last time it received the archive?

Consider how the GDC can ensure that the archive is complete and unzipable before sending it

**Comment by kaiwirt** [comment]
I was wondering if this is a duplicate of #16 ?

Do we need two metrics, one for metadata and one for the archive? See also the comment from @aschremm in #16 
I only recall that we wanted to have an alert when the archive is not received by the GC for more than 24 hours....

@tomkralidis

**Comment by tomkralidis** [comment]
@kaiwirt we have `wmo_wis2_gc_last_metadata_timestamp_seconds` as part of GC metrics. Can we define a rule to trigger an alert when the timestamp is older than 24 hours?

**Comment by kaiwirt** [comment]
This could be added to https://github.com/wmo-im/wis2-metric-hierarchy/blob/main/alerts/gc.yml

**Comment by antje-s** [comment]
Currently we do not use the metric wmo_wis2_gc_last_metadata_timestamp_seconds for the zip-archive but set the timestamp for the last download of a metadata record per centre_id
