### ISSUE TITLE
add GC metric of last metadata record 

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-metric-hierarchy#16]
As discussed at the Global Services Testing May 2024 meeting in Tokyo, add Global Cache metric for last metadata record (by centre-id) to facilitate resume workflow by GDCs.

**Comment by antje-s** [comment]
One query for clarification:
Should the metric include the timestamp of the last receipt of zip-archiv from GDC (label for each GDC) OR should it include timestamp of the last receipt of metadata record from centre (label for each centre-id)?

If it is for the zip archives, should the criterion be ("global-discovery-catalogue" in centre-id and links type is "application/zip")?
Unless there is a more elegant solution we would have to check all received messages for messages that are only expected once a day. I think perhaps a metric from the GDC might be a better solution. 
In contrast, the GDC is the appropriate source if the metric is intended for each metadata set.
