### ISSUE TITLE
List of services / acronyms

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-metric-hierarchy#2]
The third level of the naming convention is the service name.
Potential options:

- Global Cache = gc
- Global Broker = gb
- Global Discovery Catalog = gdc
- Global Monitoring = gm
- Wis2 node = wn

others?

**Comment by kaiwirt** [comment]
The current list of services (subject to discussion) is in https://github.com/wmo-im/wis2-metric-hierarchy/blob/main/metric-hierarchy/wis2.csv

**Comment by 6a6d74** [comment]
This will be part of the discussion on monitoring. To be picked up after INFCOM3.

**Comment by 6a6d74** [comment]
@golfvert will update the section in the Guide for Global Cache to list the metrics that have already been agreed. Then we can close this issue.

**Comment by golfvert** [comment]
Completed with https://github.com/wmo-im/wis2-guide/pull/79.
