### ISSUE TITLE
Proposal to add a label dataserver to metric wmo_wis2_gc_downloaded_errors_total

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-metric-hierarchy#24]
Currently it is not possible to see from the metrics whether the download error occurred at the originator centre or at one of the caches, so I would suggest adding a label dataserver to the metric wmo_wis2_gc_downloaded_errors_total

**Comment by jmaxmarno** [comment]
This seems appropriate and wouldn't be a huge lift
